# Generated by Django 5.1.2 on 2024-10-19 20:04

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("user", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="post_images")),
                ("caption", models.TextField()),
                ("create_at", models.DateTimeField(default=datetime.datetime.now)),
                ("no_of_likes", models.IntegerField(default=0)),
            ],
        ),
    ]
